158-addSystematikbuchA-20230626-Teil 1/2
hbz/lobid-vocabs pull request #169
Opened 2023-06-26 08:00 UTC by HMetzner

Heute am Nachmittag kommt Teil 2/2

2023-06-26 08:50 UTC, fsteeg requested changes
Habe ein paar kleine Vorschläge gemacht, die müsstest du über die Oberfläche direkt committen können (z.B. erst jeweils "Add suggestion to batch", dann in einem commit, oder einzeln auf "Commit suggestion").

Ansonsten ist mir noch aufgefallen, dass die Groß-/Klein­schrei­bung am Anfang nicht ganz konsistent ist (s.a., S.a., ...).

2023-06-26 08:50 UTC, fsteeg commented on nwbib/nwbib.ttl
> +    skos:scopeNote "Wenn militärisch behandelt wird"@de, "s.a. [Sachgebiet Burgen.Schlösser](https://nwbib.de/subjects#N844040)"@de ;
```suggestion
    skos:scopeNote "Wenn militärisch behandelt wird"@de, "s.a. [Sachgebiet Burgen. Schlösser](https://nwbib.de/subjects#N844040)"@de ;
```

2023-06-26 08:50 UTC, fsteeg commented on nwbib/nwbib.ttl
> +    skos:scopeNote "Benutzt für moderne u. historische Personenstandsverz., ggf. zusätzl. [Quellen](https://nwbib.de/subjects#N240100) u. [Kirchengemeinden](https://nwbib.de/subjects#N611030 o. https
```suggestion
    skos:scopeNote "Benutzt für moderne u. historische Personenstandsverz., ggf. zusätzl. [Quellen](https://nwbib.de/subjects#N240100) u. [katholische](https://nwbib.de/subjects#N611030) o. [evangelische](https://nwbib.de/subjects#N613030) Kirchengemeinden"@de .
```

2023-06-26 08:50 UTC, fsteeg commented on nwbib/nwbib.ttl
> +    skos:scopeNote "s.a. [Tod.Bestattung](https://nwbib.de/subjects#N704064)"@de .
```suggestion
    skos:scopeNote "s.a. [Tod. Bestattung](https://nwbib.de/subjects#N704064)"@de .
```

2023-06-26 12:07 UTC, HMetzner commented
Danke. Hab ich durchgesehen und geändert. Die Kleinschreibung kontrolliere ich nochmal.

2023-06-27 09:12 UTC, fsteeg requested changes
Habe noch ein paar Kleinigkeiten als Vorschläge ergänzt.

(Über 'Add suggestion to batch' kannst du die auch sammeln, um dann z.B. nur einen Commit zu erzeugen, oder nur die `;`-Änderungen in einen Commit, etc.; du kannst die aber auch wie gestern einzeln annehmen.)

2023-06-27 09:12 UTC, fsteeg commented on nwbib/nwbib.ttl
> +    skos:scopeNote "Freie SW: Winter, Brauchtum"@de .
```suggestion
    skos:scopeNote "Freie SW: Winter; Brauchtum"@de .
```

2023-06-27 09:12 UTC, fsteeg commented on nwbib/nwbib.ttl
> +    skos:scopeNote "Freie SW: Ernte, Brauchtum"@de .
```suggestion
    skos:scopeNote "Freie SW: Ernte; Brauchtum"@de .
```

2023-06-27 09:12 UTC, fsteeg commented on nwbib/nwbib.ttl
> +    skos:scopeNote "Freie SW: Hochzeit, Brauchtum"@de .
```suggestion
    skos:scopeNote "Freie SW: Hochzeit; Brauchtum"@de .
```

2023-06-27 09:12 UTC, fsteeg commented on nwbib/nwbib.ttl
> +    skos:scopeNote "Freie SW: Tod, Brauchtum; s.a. [Bestattungswesen](https://nwbib.de/subjects#N617000)"@de .
```suggestion
    skos:scopeNote "Freie SW: Tod; Brauchtum; s.a. [Bestattungswesen](https://nwbib.de/subjects#N617000)"@de .
```

2023-06-27 09:12 UTC, fsteeg commented on nwbib/nwbib.ttl
> +    skos:scopeNote "Freie SW: Homosexualität, Prostitution etc."@de .
```suggestion
    skos:scopeNote "Freie SW: Homosexualität; Prostitution etc."@de .
```

2023-07-04 08:23 UTC, fsteeg approved these changes

2023-07-04 08:23 UTC, merged