AddSystematikbuchA (#158) 20230703
hbz/lobid-vocabs pull request #170
Opened 2023-07-03 08:25 UTC by HMetzner

Hier hätte ein Commit gereicht, oder? Entschuldige bitte das Durcheinander. Systematikbuch A ist hiermit abgeschlossen. Es folgt Systematikbuch B (#165). Das mache ich dann als neuen PR, da es ein neues Ticket betrifft.

2023-07-04 09:20 UTC, fsteeg requested changes
Klasse, die klingen sehr hilfreich die Verwendungshinweise!

> Hier hätte ein Commit gereicht, oder? Entschuldige bitte das Durcheinander.

Also das sieht prima aus, sind ja verschiedene Commit-Messages, die sich ja auch noch auf verschiedene Issues beziehen. (Gute Kandidaten zum Zusammenfassen sind Commits, für die man identische Messages schreibt.) Und ich kann im "Files changed"-Tab sowieso alles auf einmal ansehen zum Reviewen. (Da könntest du übrigens auch einzelne Commit-Vorschläge von mir zusammenfassen bevor du sie annimmst.)

Zu ein paar kleinen Tipp-/Copy-Paste-/Syntaxfehlern habe ich hier direkt Vorschläge gemacht. (Wie neulich besprochen nach der Annahme dieser Änderungen erstmal `git pull`, dann eigene Änderungen machen.)

Und was noch systematisch falsch zu sein scheint ist der Link `zu allg. [Geschichte](https://nwbib.de/subjects#N704070)`, das müsste wohl immer zu https://nwbib.de/subjects#N240000 gehen.

2023-07-04 09:20 UTC, fsteeg commented on nwbib/nwbib.ttl
> +	skos:editorialNote "Nicht bei Baudenkmälern anwenden, dafür s. entspr. Notation unter [Baudenkmäler.Kunstwerke](https://nwbib.de/subjects#N844000)"@de ;
```suggestion
	skos:editorialNote "Nicht bei Baudenkmälern anwenden, dafür s. entspr. Notation unter [Baudenkmäler. Kunstwerke](https://nwbib.de/subjects#N844000)"@de ;
```

2023-07-04 09:20 UTC, fsteeg commented on nwbib/nwbib.ttl
> +    skos:scopeNote "Freie SW: Kunstmuseum; Kunstsammlungen"@de .
```suggestion
    skos:scopeNote "Freie SW: Kunstmuseum; Kunstsammlung"@de .
```

2023-07-04 09:20 UTC, fsteeg commented on nwbib/nwbib.ttl
> +    skos:scopeNote "Verwenden bei Gartenkunst; Freie SW: Gartenkunst; S.a. Grünanlagen [Parks](https://nwbib.de/subjects#N704070)"@de .
```suggestion
    skos:scopeNote "Verwenden bei Gartenkunst; Freie SW: Gartenkunst; S.a. [Grünanlagen](https://nwbib.de/subjects#N586000); [Parks](https://nwbib.de/subjects#N586020)"@de .
```

2023-07-06 06:43 UTC, HMetzner commented
Die Änderung der Notation "Geschichte" folgt noch.

2023-07-06 07:00 UTC, HMetzner commented
Wie ärgerlich, dass mir dieser Folgefehler unterlaufen ist. Es ist wirklich gut, dass ihr da nochmal drüberschaut! 
Bei den Grünanlagen/Parks (https://nwbib.de/subjects#N586020) geht es darum, dass die Parks unter dem Oberbegriff "Grünanlagen" verwendet werden. (Im Unterschied zu Park- und Gartenanlagen (844060)) Aber es müssen nicht Grünanlagen (586000) UND Parks (586020) verwendet werden. Ich verstehe, dass die Formulierung Grünanlagen [Parks](https://nwbib.de/subjects#N704070) missverständlich war.

2023-07-07 09:22 UTC, fsteeg commented
> Wie ärgerlich, dass mir dieser Folgefehler unterlaufen ist. Es ist wirklich gut, dass ihr da nochmal drüberschaut!

Ja, und deshalb auch gar nicht schlimm, ist doch als Reviewer auch schön, wenn man was findet :-)

> Bei den Grünanlagen/Parks (https://nwbib.de/subjects#N586020) geht es darum, dass die [Parks](https://nwbib.de/subjects#N704070) unter dem Oberbegriff "Grünanlagen" verwendet werden. (Im Unterschied zu Park- und Gartenanlagen (844060)) Aber es müssen nicht Grünanlagen (586000) UND Parks (586020) verwendet werden. Ich verstehe, dass die Formulierung Grünanlagen Parks missverständlich war.

Verstehe, ich hatte auch eigentlich nur den Link fixen wollen (ging zu Schützenwesen), und dachte dann Grünanlagen kann man doch auch verlinken. Aber prima, du hattest ja die Änderung erst angenommen, dadurch stimmt der Link auch weiterhin.

Und schön mit den zusammengefassten Vorschlägen, sehr übersichtlich mit den 2 neuen Commits!

2023-07-07 09:22 UTC, fsteeg approved these changes

2023-07-07 09:22 UTC, merged