VerweisÄhnlicheUndMehrfachGenutzteNotationen (#173)
hbz/lobid-vocabs pull request #182
Opened 2023-07-10 08:38 UTC by HMetzner

2023-07-10 10:17 UTC, fsteeg requested changes
Sieht prima aus insgesamt!

Habe nur Vorschläge zu einem Tippfehler und zur Darstellung der Links zu den vers. Germanen etc. gemacht (227040, das auf `Franken (Römerzeit)` verweisen würde, scheint irgendwie in der Datei zu fehlen, im Systematik-Baum ist es aber da).

Ansonsten bekomme ich hier noch eine Warnung wegen dem Umlaut im Branch-Namen, scheint trotzdem zu gehen, sollte man aber wahrscheinlich eher vermeiden.

2023-07-10 10:17 UTC, fsteeg commented on nwbib/nwbib.ttl
> +    skos:scopeNote "S.a. [Römer](https://nwbib.de/subjects#N227020)"@de ;
```suggestion
    skos:scopeNote "S.a. [Römer (Völkerwanderungszeit)](https://nwbib.de/subjects#N227020)"@de ;
```

2023-07-10 14:41 UTC, HMetzner commented
ich füge noch die Hinweise für "Kelten" ein

2023-07-10 14:45 UTC, HMetzner commented
Einen Change von dir hatte ich übersehen (226030 Römer). Hab ihn jetzt committed.

2023-07-11 09:07 UTC, fsteeg approved these changes

2023-07-11 09:08 UTC, merged